name: Build and Test

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.0
      - run: git checkout main && git checkout $GITHUB_SHA
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm test
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: pnpm exec changeset status
